name: docker-build

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Docker image
        run: |
          docker build -t hold-my-place .
